project:
  type: website
  output-dir: docs
  resources:
    - figures/
    
website:
  title: "PODFRIDGE-Databases"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - text: Analyses
        menu:
          - href: qmd_root/ndis_scraping.html
            text: NDIS scraping methodology
          - href: qmd_root/ndis_analysis.html
            text: NDIS analysis
          - href: qmd_root/sdis_summary.html
            text: SDIS summary
          - href: qmd_root/foia_processing.html
            text: FOIA processing
          - href: qmd_root/appendix_analysis.html
            text: Annual DNA Collection
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css     
    toc: true
