project:
  type: website
  output-dir: docs
  resources:
    - figures/
  
execute:
    freeze: auto  # Only re-execute when source changes
    
website:
  title: "PODFRIDGE-Databases"
  site-url: https://tinalasisi.github.io/PODFRIDGE-Databases
  navbar:
    right:
      - icon: github
        href: https://github.com/tinalasisi/PODFRIDGE-Databases
        text: Source
    left:
      - href: index.html
        text: Home
      - text: Analyses
        menu:
          - href: analysis/ndis_scraping.html
            text: NDIS scraping methodology
          - href: analysis/ndis_analysis.html
            text: NDIS analysis
          - href: analysis/sdis_summary.html
            text: SDIS summary
          - href: analysis/foia_processing.html
            text: FOIA processing
          - href: analysis/appendix_analysis.html
            text: Annual DNA Collection
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css     
    toc: true
